
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightDOTleftRPARrightLPARleftVARleftAPLDOT LAMBDA LPAR RPAR VAR\n    Termo : Termo Termo  %prec APL\n          | LPAR Termo Termo RPAR\n    \n    Termo : LAMBDA VAR DOT Termo\n          | LPAR LAMBDA VAR DOT Termo RPAR\n    \n    Termo : VAR\n          | LPAR VAR LPAR\n    '
    
_lr_action_items = {'LPAR':([0,1,3,4,6,7,9,11,12,13,14,15,16,17,18,],[1,1,1,-5,1,-5,-1,-1,-6,1,1,-2,1,1,-4,]),'LAMBDA':([0,1,3,4,6,7,9,11,12,13,14,15,16,17,18,],[2,5,2,-5,2,-5,-1,-1,-6,2,2,-2,-3,-3,-4,]),'$end':([3,4,9,12,15,16,18,],[0,-5,-1,-6,-2,-3,-4,]),'RPAR':([4,9,11,12,15,16,17,18,],[-5,-1,15,-6,-2,-3,18,-4,]),'VAR':([0,1,2,3,4,5,6,7,9,11,12,13,14,15,16,17,18,],[4,7,8,4,-5,10,4,-5,-1,-1,-6,4,4,-2,4,4,-4,]),'DOT':([8,10,],[13,14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Termo':([0,1,3,6,9,11,13,14,16,17,],[3,6,9,11,9,9,16,17,9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Termo","S'",1,None,None,None),
  ('Termo -> Termo Termo','Termo',2,'p_aplicacao','parser.py',15),
  ('Termo -> LPAR Termo Termo RPAR','Termo',4,'p_aplicacao','parser.py',16),
  ('Termo -> LAMBDA VAR DOT Termo','Termo',4,'p_abstracao','parser.py',27),
  ('Termo -> LPAR LAMBDA VAR DOT Termo RPAR','Termo',6,'p_abstracao','parser.py',28),
  ('Termo -> VAR','Termo',1,'p_variavel','parser.py',45),
  ('Termo -> LPAR VAR LPAR','Termo',3,'p_variavel','parser.py',46),
]
